### ISSUE TITLE
Does it need to remove the notificationCenter observer or not?

### ISSUE THREAD

**Issue by peace-v** [strawberrycode/SafariOauthLogin#1]
Hi, I viewed your blog and want to post a comment, but somehow it did't show after post, so I just directly create an issue in Github. 

There is nothing wrong happened when following your instruction, but I have an question -- you add the notificationCenter observer in viewController's viewDidLoad method, but I can't find in the code of removing observer.

I tried in my app to remover the observer in viewWillDisappear, but if do so, the viewController will never receive the notification. After google it, I found a post in stackoverflow http://stackoverflow.com/questions/25497928/dealloc-in-swift , it said can remove the observer in deinit method and actually no need to remove it since iOS9.

So I'm wondering do we need to remove the observer or not. If yes, how can we remove it and keep the viewController can receive the notification? Call it in deinit?

**Comment by strawberrycode** [comment]
Hi, thanks for your question (I'll double check the blog too).

So, to answer your question, if/when your observer is not useful anymore, you _can_ remove it so it will stop listening to notifications, it is still supported. But you are right, as mentioned in the [iOS9 prerelease notes](https://developer.apple.com/library/prerelease/mac/releasenotes/Foundation/RN-Foundation/index.html#10_11NotificationCenter) you don't need to deallocate the observer anymore, unless you use it with a `Block` syntax because of the strong reference to it.

If you still wish to remove the observer, I've found a pretty interesting article from @natashatherobot which may help you: [Where To Remove Observer for NSNotification in Swift](https://www.natashatherobot.com/ios8-where-to-remove-observer-for-nsnotification-in-swift/)

I hope this helps :)

**Comment by peace-v** [comment]
Thanks for your reply. It solved my doubts. :)
